server {
    listen 80;
    client_max_body_size 50M;

    location / {
        proxy_pass http://api:5000;
        proxy_set_header Host $host;
    }

    location /output/ {
        alias /app/output/;
        add_header Content-Disposition attachment;
    }
}
